# The UUID for the multiverse world the plugin should work in, aka. The Catacombs world
multiverse-world-UID: ""
# A list of all the items that should be ignored when adding loot to the reward pool
# type: "namespace:item_key"
catacomb-item-filter: []
# A list of the items that will be offered to the winner of the Catacombs. This list is managed automatically
# type: ["namespace:item_key", "number(amount)"]
catacomb-prize-pool: []
