name: EarthCatacombs
version: 1.0
main: me.wholesome_seal.jasonbourne.JasonBourne
api-version: 1.19
authors: [wholesome_seal]

commands:
  catacomb:
    description: "The manager for the Catacomb plugin commands"
    permission: earthcatacombs.catacomb

permissions:
  earthcatacombs.catacomb:
    description: Permission to run all /catacomb subcommands. Admin command
  earthcatacombs.*:
    description: Wildcard permission for all commands
    children:
      earthcatacombs.catacomb: true
