name: EarthCatacombs
version: 1.0
main: me.wholesome_seal.jasonbourne.JasonBourne
api-version: 1.19
authors: [wholesome_seal]

commands:
  catacomb:
    description: "The manager for the Catacomb plugin commands"
